name: Daily Email Automation

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js
        env:
          SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
          SENDGRID_EMAIL: ${{ secrets.SENDGRID_EMAIL }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}